server:
  port: 8082

spring:
  aop:
    proxy-target-class: true
  dubbo:
    application:
      name: ssoService
    registry:
      address: zookeeper://120.79.254.32:2181
    protocol:
      name: dubbo
      port: 20882
    scan: com.lzg.sso.service,com.lzg.sso.controller
#配置druid配置源
  jpa:
    show-sql: true
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.254.32:3306/benniu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters:
       commons-log.connection-logger-name: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# Redis服务器地址
#spring.redis.host=10.100.50.23
# Redis服务器连接端口
#spring.redis.port=6379
# Redis服务器连接密码（默认为空）
  redis:
    password:
# redis.cluster
    cluster:
      nodes: 120.79.254.32:7001,120.79.254.32:7002,120.79.254.32:7003,120.79.254.32:7004,120.79.254.32:7005,120.79.254.32:7006
