#…Ë÷√∂Àø⁄£¨±‹√‚≥ÂÕª
server:
  port: 8082
#≈‰÷√dubbo
spring:
  aop:
    proxy-target-class: false
  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://120.79.254.32:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.lzg.manager.service
#    ≈‰÷√druid≈‰÷√‘¥
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/tbook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters:
       commons-log.connection-logger-name: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500